name: Build and deploy Nest.js app to Azure Web App

on:
  push:
    branches:
    - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm install, build, and test
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      - name: Zip all files for upload between jobs
        run: zip --symlinks -r nest.zip ./dist/*
                
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ secrets.DEV_AZURE_APP_API_NAME }}
          path: nest.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.DEV_AZURE_APP_API_NAME }}
          publish-profile: ${{ secrets.DEV_AZURE_PUBLISH_PROFILE_API }}
          package: nest.zip

      - name: Delete zip file
        run: rm nest.zip